### Site Settings ###
title               : Mohd Kashif
description         : "Cybersecurity Professional | Threat Hunting | SOC"
"Masterâ€™s graduate in Cybersecurity with over four years of experience in security operations,
specializing in 24/7 incident response, vulnerability assessment and proactive threat detection. Skilled
in Microsoft Defender, SIEM, and EDR tools with proven ability to triage incidents, collaborate
with cross-functional teams, and develop detection rules to further hardening the systems."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : eliteCipher/eliteCipher.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                        
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Mohd Kashif
  image             : assets/mkashif.jpg
# behance           : your_username
# dribbble          : your_username
  email             : hello@mkashif.me
#  facebook          : 
  github            : eliteCipher
  keybase           : mkashif_
# gitlab            : your_username
# instagram         : your_username
  linkedin          : penkashif
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : 
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


  publications:
    output: true
    permalink: /publications/:title


### Disqus ###
disqus: mkashif


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                          
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"          # Set false to disable comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
